# This file was first automatically generated by gen-acme-cpanmodules-module-from-acme-cpanlists-list on Sat Sep 22 07:59:40 2018 from module list in Acme::CPANLists::Import::BKB::CheckMemory version 0.001.

package Acme::CPANModules::Import::BKB::CheckMemory;

# DATE
# VERSION

our $LIST = {
  description => "This list is generated by extracting module names mentioned in [https://www.lemoda.net/perl/memory-check-modules/index.html] (retrieved on 2017-03-27). Visit the URL for the full contents.",
  entries     => [
                   { module => "Devel::GDB" },
                   { module => "Devel::Leak" },
                   { module => "Devel::LeakTrace" },
                   { module => "Devel::LeakTrace::Fast" },
                   { module => "Devel::MAT" },
                   { module => "Devel::Plumber" },
                   { module => "Devel::Valgrind::Client" },
                   { module => "Test::LeakTrace" },
                   { module => "Test::MemoryGrowth" },
                   { module => "Test::NoLeaks" },
                   { module => "Test::RunValgrind" },
                   { module => "Test::Valgrind" },
                 ],
  summary     => "Perl modules for checking memory (2017)",
};

1;
# ABSTRACT: Perl modules for checking memory (2017)

