# This file was first automatically generated by gen-acme-cpanmodules-module-from-acme-cpanlists-list on Sat Sep 22 07:59:40 2018 from module list in Acme::CPANLists::Import::BKB::FindMIMEType version 0.001.

package Acme::CPANModules::Import::BKB::FindMIMEType;

# DATE
# VERSION

our $LIST = {
  description => "This list is generated by extracting module names mentioned in [https://www.lemoda.net/perl/find-type-of-file/] (retrieved on 2017-03-27). Visit the URL for the full contents.",
  entries     => [
                   { module => "File::LibMagic" },
                   { module => "File::LibMagic::FFI" },
                   { module => "File::MMagic" },
                   { module => "File::MMagic::XS" },
                   { module => "File::MimeInfo" },
                   { module => "File::Type" },
                   { module => "File::Type::WebImages" },
                   { module => "MIME::Detect" },
                   { module => "MIME::Type::FileName" },
                   { module => "MIME::Types" },
                   { module => "Media::Type::Simple" },
                   { module => "Padre::MIME" },
                 ],
  summary     => "Perl modules to find the MIME type of a file (2017)",
};

1;
# ABSTRACT: Perl modules to find the MIME type of a file (2017)

