# This file was first automatically generated by gen-acme-cpanmodules-module-from-acme-cpanlists-list on Sat Sep 22 07:59:40 2018 from module list in Acme::CPANLists::Import::BKB::FindDependencies version 0.001.

package Acme::CPANModules::Import::BKB::FindDependencies;

# DATE
# VERSION

our $LIST = {
  description => "This list is generated by extracting module names mentioned in [https://www.lemoda.net/perl/perl-dependencies/index.html] (retrieved on 2017-03-27). Visit the URL for the full contents.",
  entries     => [
                   { module => "Devel::Loaded" },
                   { module => "Module::Extract::Use" },
                   { module => "Module::ExtractUse" },
                   { module => "Module::Info" },
                   { module => "Module::Metadata" },
                   { module => "Module::ScanDeps" },
                   { module => "Module::Used" },
                 ],
  summary     => "Modules for finding Perl dependencies (2017)",
};

1;
# ABSTRACT: Modules for finding Perl dependencies (2017)

