# This file was first automatically generated by gen-acme-cpanmodules-module-from-acme-cpanlists-list on Sat Sep 22 07:59:40 2018 from module list in Acme::CPANLists::Import::BKB::Handy version 0.001.

package Acme::CPANModules::Import::BKB::Handy;

# DATE
# VERSION

our $LIST = {
  description => "This list is generated by extracting module names mentioned in [https://www.lemoda.net/perl/handy-modules/index.html] (retrieved on 2017-03-27). Visit the URL for the full contents.",
  entries     => [
                   { module => "App::cpanminus" },
                   { module => "CGI" },
                   { module => "Carp" },
                   { module => "DBD::SQLite" },
                   { module => "DBD::mysql" },
                   { module => "DBI" },
                   { module => "ExtUtils::MakeMaker" },
                   { module => "File::Copy" },
                   { module => "File::Find" },
                   { module => "File::Spec" },
                   { module => "File::Temp" },
                   { module => "FindBin" },
                   { module => "Module::Build" },
                   { module => "Template" },
                   { module => "Test" },
                   { module => "Test::More" },
                   { module => "Test::Simple" },
                 ],
  summary     => "Handy Perl modules (2011)",
};

1;
# ABSTRACT: Handy Perl modules (2011)

