# This file was first automatically generated by gen-acme-cpanmodules-module-from-acme-cpanlists-list on Sat Sep 22 07:59:41 2018 from module list in Acme::CPANLists::Import::BKB::Japanese version 0.001.

package Acme::CPANModules::Import::BKB::Japanese;

# DATE
# VERSION

our $LIST = {
  description => "This list is generated by extracting module names mentioned in [https://www.lemoda.net/perl/cpan-japanese-language/index.html] (retrieved on 2017-03-27). Visit the URL for the full contents.",
  entries     => [
                   { module => "DateTime::Calendar::Japanese::Era" },
                   { module => "Lingua::JA::FindDates" },
                   { module => "Lingua::JA::Moji" },
                   { module => "Lingua::JA::Numbers" },
                   { module => "Lingua::JA::Yomi" },
                   { module => "Text::MeCab" },
                 ],
  summary     => "CPAN modules for dealing with the Japanese language (2012)",
};

1;
# ABSTRACT: CPAN modules for dealing with the Japanese language (2012)

