# This file was first automatically generated by gen-acme-cpanmodules-module-from-acme-cpanlists-list on Sat Sep 22 07:59:41 2018 from module list in Acme::CPANLists::Import::BKB::RemoveHTMLTags version 0.001.

package Acme::CPANModules::Import::BKB::RemoveHTMLTags;

# DATE
# VERSION

our $LIST = {
  description => "This list is generated by extracting module names mentioned in [https://www.lemoda.net/perl/html-cleanup-modules/index.html] (retrieved on 2017-03-27). Visit the URL for the full contents.",
  entries     => [
                   { module => "HTML::Defang" },
                   { module => "HTML::Detoxifier" },
                   { module => "HTML::Laundry" },
                   { module => "HTML::Restrict" },
                   { module => "HTML::Scrubber" },
                   { module => "HTML::Strip" },
                   { module => "HTML::TagFilter" },
                   { module => "HTML::Truncate" },
                   { module => "MojoMojo::Declaw" },
                 ],
  summary     => "Perl modules to remove HTML tags (2017)",
};

1;
# ABSTRACT: Perl modules to remove HTML tags (2017)

